name: central-experiment-launcher
port: 8000
description: Parametrize and launch an experiment of a chosen flow

replicas:
  min: 1
  max: 1

commands:
  - streamlit run deployments/central-experiment-launcher/app.py --server.port 8000

dependencies:
  from_requirements_file: deployments/central-experiment-launcher/requirements.txt
