name: experiment-launcher
port: 8000
description: Parametrize and launch an experiment

replicas:
  min: 1
  max: 1

commands:
  - streamlit run deployments/experiment-launcher/app.py --server.port 8000

dependencies:
  from_requirements_file: deployments/experiment-launcher/requirements.txt
